### ISSUE TITLE
Refresh 

### ISSUE THREAD

**Issue by TeslaOwnerTips** [TeslaBuds/AuthAppForTesla#10]
The refresh button no longer does anything. 
Thank you for the app.

**Comment by Kemmey** [comment]
It should refresh your access token - you can see that it has refreshed by the token validity resetting to 8 hours. 

Usually you should not need to tap refresh at all though - this happens automatically - even when using the shortcuts actions 

Cheers,

Kim

**Comment by TeslaOwnerTips** [comment]
Before and after “Refresh Token”
![17D81A19-C99E-46AC-BE8B-DD09C29CCA10](https://user-images.githubusercontent.com/78335749/140258345-a94d3fef-6250-4165-a4b6-7a66243711e2.png)

**Comment by Kemmey** [comment]
Please don't post tokens online :-D 

Is this the access token or the refresh token? The refresh token almost never change, and certainly not when tapping refresh tokens :-D

**Comment by TeslaOwnerTips** [comment]
It’s not the entire token. 
Is there still a way to revoke tokens other than charging the Tesla account password?

**Comment by Kemmey** [comment]
No - unfortunately not - still waiting for Tesla to implement and expose proper OAuth where we'll be able to register out applications and reply urls. When they do - this app can happily be decommissioned :-D

**Comment by Kemmey** [comment]
But I suspect your screenshots above were for the refresh token, right? They don't change at refresh - I've rarely seen them change. I'm not sure they even have an expiration time. But access tokens properly change - also when manually refreshing - have triple checked and confirmed.

**Comment by TeslaOwnerTips** [comment]
Okay thanks. It said Refresh Tokens plural.

**Comment by Kemmey** [comment]
Oh - it DOES refresh all three tokens - it refreshes the refresh token, the v3 access token and the v2 access token (no longer exposed in ui as it is considered deprecated - still accessible via shortcuts. 

But the refresh token very rarely changes - during a refresh it is the server that controls what to send back - if server does not deem it necessary to issue a new refresh token - you will just get the old one back. That does not mean it is not refreshed...
