### ISSUE TITLE
Shortcuts - Incorrect name/label Owner Token 

### ISSUE THREAD

**Issue by TeslaOwnerTips** [TeslaBuds/AuthAppForTesla#11]
Thanks for implementing this!

After adding to the shortcut 
Get *Owner* Token shows as Got *Access* Token 
*Get Access Token* also shows as *Got Access Token*

Also
The *Got* XYZ does not follow Apple’s and all other apps naming/labeling convention which use *Get* XYZ 

Edit: Removed video because it wasn’t the correct one.

**Comment by TeslaOwnerTips** [comment]
Updated video 

https://user-images.githubusercontent.com/78335749/140310328-e9aa1b6f-03e2-4c6e-a8c8-7c6b1fc26aba.MP4

**Comment by Kemmey** [comment]
Fixed in TestFlight - I had all the intents correctly named - but the "Summary" fields apparently ACTUALLY control the title field - not the "Title" field... 

Grab TestFlight build here: 

https://testflight.apple.com/join/jTixIetK

**Comment by TeslaOwnerTips** [comment]
Thanks. Any ETA on when it will be updated in the App Store?

**Comment by Kemmey** [comment]
Once fix has been verified from TestFlight build...

Then I'll submit a build and then it's just a matter of awaiting apple approval

**Comment by Kemmey** [comment]
Submitted to the store - awaiting review
