### ISSUE TITLE
Refresh Token shows Access Token 

### ISSUE THREAD

**Issue by Krillle** [TeslaBuds/AuthAppForTesla#19]
It looks to me like the section Refresh Token shows the same token as the section Access Token, which is a working Access Token. Means the section Refresh Token shows the Access Token as well, not the Refresh Token. 
![6380FD51-D45C-4511-A5EB-3B75B0FFB4E8](https://user-images.githubusercontent.com/2863110/147751183-7010f438-d8db-4264-8261-f30ad6ea7ac7.jpeg)

**Comment by Kemmey** [comment]
The tokens are similar, but if you compare them with a text editor they are different.

**Comment by Krillle** [comment]
Yes indeed. You are right.
